log:
  level: DEBUG 
  filePath: "/var/log/traefik.log"
accessLog:
  filePath: "/var/log/traefikaccess.log"
  bufferingSize: 250
  format: json
api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    http:
      tls:
        certResolver: letsencrypt
  #dashboard:
    #address: ":5771"
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_proxy
  file:
    directory: "/srv/docker-compose/traefik_config"
    watch:
      true

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'isaccounts@diversityarrays.com'
      storage: /srv/docker-compose/ssl-encrypt/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
