version: "3.8"
services:
  monitoring-portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    profiles:
      - "monitoring"
      - "all"
    command: -H unix:///var/run/docker.sock
    restart: always
    env_file:
      - ./env/timezone.env
      - ./env/userpermissions.env
    deploy:
      resources:
          limits:
            cpus: '0.5'
            memory: 256M
          reservations:
            cpus: '0.1'
            memory: 128M
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik_proxy:
    external: true

volumes:
  portainer_data:
    external: true