version: "3.8"
services:
  monitoring-glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    profiles:
      - "monitoring"
      - "all"
    pid: host
    env_file:
      - ./env/timezone.env
    environment:
      - "GLANCES_OPT=-w"
    deploy:
      resources:
          limits:
            cpus: '0.5'
            memory: 256M
          reservations:
            cpus: '0.1'
            memory: 128m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.glances.loadbalancer.passhostheader=true"

networks:
  traefik_proxy:
    external: true