http:
    routers:
        portainer:
            rule: 
                "Host(`{{env "PORTAINER_URL"}}`)"
            tls:
                certResolver: letsencrypt
            entryPoints:
                websecure
            service: "portainer@docker"
            middlewares:
                - "admin-allow@file"
                - "rate-limiter@file"