http:
    routers:
        glances:
            rule: 
                "Host(`{{env "GLANCES_URL"}}`)"
            tls:
                certResolver: letsencrypt
            entryPoints:
                websecure
            service: "glances@docker"
            middlewares:
                - "admin-allow@file"
                - "rate-limiter@file"