http:
    routers:
        dozzle:
            rule: 
                "Host(`{{env "DOZZLE_URL"}}`)"
            tls:
                certResolver: letsencrypt
            entryPoints:
                websecure
            service: "dozzle@docker"
            middlewares:
                - "admin-allow@file"
                - "rate-limiter@file"